from . import menyuKeyboard
from . import pmenyuKeyboard 
from . import fmenyuKeyboard
from . import gmenyuKeyboard
from . import dmenyuKeyboard
from . import backKeyboard
from . import phpKeyboard
from . import javaKeyboard
from . import k_Keyboard
from . import ksKeyboard
from . import komsKeyboard
from . import word_Keyboard
from . import exel_Keyboard
from .import powerKeyboard
from . import mobilKeyboard
from . import aosKeyboard
from . import androidKeyboard
from . import flutterKeyboard
from . import mbazaKeyboard
from . import mysqlKeyboard
from . import sqlKeyboard
from . import postKeyboard
from . import exel2
